# This would chang eto craterapp/crater-php once the PR is merged
# https://github.com/crater-invoice/crater/pull/922
FROM bahmni/crater-php:product-1.0.0

COPY /database/seeders /var/www/database/seeders
